// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewAssignment struct {
	Name     string `json:"name"`
	CourseID int    `json:"courseId"`
	TermID   int    `json:"termId"`
	GroupID  int    `json:"groupId"`
}

type NewAssignmentGroup struct {
	Name     string `json:"name"`
	CourseID int    `json:"courseId"`
	TermID   int    `json:"termId"`
}

type NewCourse struct {
	Name    string `json:"name"`
	LevelID int    `json:"levelId"`
}

type NewTerm struct {
	Name       string `json:"name"`
	SchoolYear int    `json:"schoolYear"`
}
