INSERT INTO level (name, created_at, updated_at) VALUES
  ('1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('12', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
